---
kind: pipeline
name: tests
type: docker

steps:
  - name: Generate overrides file
    image: python:3.8-alpine
    commands:
      - pip3 install 'pipenv==2018.11.26'
      - pipenv install --system
      - python3 generate.py testdata 
  
  - name: Validate overrides file
    image: prom/prometheus:v2.16.0
    commands:
      - promtool check rules overrides.rules

---
kind: pipeline
name: build
type: docker

steps:  
  - name: build docker image (latest)
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_user
      password:
        from_secret: docker_pw
      repo: wbh1/prom_rule_overrider
      tags:
        - latest
    when:
      branch:
        - master
      event:
        - push

  - name: build docker image (tagged)
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_user
      password:
        from_secret: docker_pw
      repo: wbh1/prom_rule_overrider
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag